### ISSUE TITLE
Specify external css source for multiple files

### ISSUE THREAD

**Issue by alexcroox** [jonkemp/gulp-inline-css#25]
I have the following folder structure for email templates

/emails/templates/header.html
/emails/templates/footer.html
/emails/welcome.html

I need to keep them split because they are used in PHP, and obviously if I run this script on welcome.html it isn't going to inline it because it has no styles from the header template.

Is there a way I can pass the build a path to the external css and it apply it to any html?

**Comment by jonkemp** [comment]
Sorry for the long delay. Can you post your gulp task or an example?

**Comment by andrewcroce** [comment]
Any follow up on this? I have the same question. I need to generate template partials (for a Ruby app) that are each individually inlined. Since the templates don't each have a stylesheet `<link>` they are not inlined.

Any way to manually supply a CSS file within the gulp task, instead of just relying on CSS linked within the html document?

**Comment by jonkemp** [comment]
@andrewcroce you could read the stylesheet into the extraCss option maybe, then run the partials through the gulp task and see if it would inline the styles.

**Comment by andrewcroce** [comment]
Yes! That does the trick thanks. Heres my gulp task, for reference:
```
gulp.task('partials', ['html'], function() {
  var css = fs.readFileSync(config.localDir + '/css/main.css', 'utf8');
  return gulp.src(config.localDir + '/partials/**/*.html')
    .pipe(inlineCss({
      extraCss: css
    }))
    .pipe(gulp.dest(config.partialsDir));
});
```

**Comment by jonkemp** [comment]
@andrewcroce nice! Closing this.
